name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: |
          cd lambda
          npm install

      - name: Compilar TypeScript
        run: |
          cd lambda
          npm run build

      - name: Salvar artefatos do build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: lambda/dist/

  test:
    name: Testes com Jest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: |
          cd lambda
          npm install

      - name: Executar testes
        run: |
          cd lambda
          npm run test

  deploy:
    name: Deploy para AWS
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar AWS SAM CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          pip install aws-sam-cli

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Altere para sua região AWS

      - name: Build com AWS SAM
        run: |
          cd lambda
          sam build

      - name: Deploy com AWS SAM
        run: |
          cd lambda
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
