jobs:
  build:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: |
          cd lambda
          npm install

      - name: Compilar TypeScript
        run: |
          cd lambda
          npm run build

      - name: Salvar artefatos do build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: lambda/dist/
